### ISSUE TITLE
Socket 연결 시 Connection Refused 현상이 발생합니다.

### ISSUE THREAD

**Issue by hongcheon95** [byungguan-yoon/pylsprotocol#1]
LS PLC와 PC 연결 시 다음 부분에서 에러가 발생 합니다.

def connect_init(self):
        conn_class = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        conn_class.connect((self.host, self.port))
        return conn_class

socket.error: [Errno 111] Connection refused

처음부터 해당 문제가 발생하는 것은 아니며 PC와 PLC 연결 시 간헐적으로 발생 합니다.

**Comment by byungguan-yoon** [comment]
안녕하세요,  @hongcheon95 님.
저도 해당 문제가 발생함을 인지하고 있었습니다. 
다만, 제가 이제 PLC를 다루는 산업군에 있지 않아 더 이상 해당 라이브러리 업데이트가 어렵습니다.

일시적인 해결 방법은 아래와 같습니다.
해당 문제는 일반적으로 PC와 PLC를 연결해놓은 상태에서 오랜 시간 통신을 주고 받지 않을 때 발생했었습니다.
따라서 일정 주기로 통신이 살아있음을 확인하는 handshake 통신을 주고 받는 방법을 사용하시길 권해드립니다.

해결 되어 좋은 서비스를 만드시길 기원합니다.
감사합니다.

**Comment by hongcheon95** [comment]
@byungguan-yoon 님, 답변 감사합니다.
말씀해주신 내용처럼 handshake 통신에 중점을 두어 문제의 원인을 검토하도록 하였습니다.
아직 해당 문제가 다시 발생하지 않아 원인을 완전히 해결된 것으로 판단할 수는 없지만 다음 이유 때문인 것으로 판단하였습니다.

현재 PC 쪽에서는 첫 연결에 대해 PLC에게 확인 신호(handshake실시)를 주지만 PC의 연결 끊김에 대해서는 따로 PLC에게 신호를 주지는 않습니다.
PC와 연결 끊김에 대한 상태를 PLC에서 따로 판단하지 않아 PLC는 기존 PC와 계속 연결된 것으로 판단하고 그 이후 PLC에서 해당 포트로 다시 연결 할 경우 동일한 포트 사용으로 차단한 것으로 생각됩니다.

위 문제를 해결하기 위해 PLC에서 주기적 PC와 연결이 되어있는 지 판단하는 로직을 이용하도록 하였습니다.

네트워크 쪽도 잘 모르는데 PLC에 대해선 더더욱 아는 것이 없어 오랫동안 붙잡고 있었네요...
말씀해주신 handshake 단어가 큰 도움이 되었습니다.

감사합니다!
